-- ============================================================
-- YBS SYSTEM: AI CACHE PROVIDER ATTRIBUTION
-- Migration: 20260925000001_ai_cache_provider_attribution.sql
--
-- Adds persistent, non-sensitive generation attribution to the AI
-- summary cache so a cached summary can report WHICH provider/model
-- actually produced it, instead of only the model id.
--
-- WHY: the edge functions return
--
--     meta: { provider, model, fallbackDepth, cached }
--
-- on a FRESH generation (values taken from the winning router route),
-- but ai_analysis_cache only persisted `model`. On a cache hit the
-- provider was therefore unknowable and had to be reported as null,
-- so an old summary rendered as
--
--     Generated by Ling 3.0 Flash Sante
--
-- while a fresh one rendered
--
--     Generated by OpenRouter · Ling 3.0 Flash Sante · Fallback #2
--
-- The provider CANNOT be reconstructed from `model`: the same model
-- string (e.g. inclusionai/ling-3.0-flash-sante:free) is served by
-- several configured routes (Novita, OpenRouter, Kilo), so any
-- derivation from the model id would be a guess that can silently
-- mislabel history. Attribution must be recorded at generation time,
-- when the winning route is actually known.
--
-- COMPATIBILITY:
--   - `model` is left untouched and remains the only column any
--     historical row is guaranteed to have.
--   - provider / fallback_depth are NULLABLE and deliberately NOT
--     backfilled. There is no correct historical value to write, so
--     pre-existing rows stay NULL and the UI shows only what is
--     known (model, no provider, no fallback depth) until the summary
--     is regenerated. NULL here means "unknown", never "not a fallback".
--   - Nothing about fingerprinting, cache matching, the stored
--     `result` payload, or invalidation changes: a cache hit remains a
--     cache hit, and re-running an unchanged assessment still returns
--     the persisted analysis without contacting any provider.
--
-- No secrets are stored: provider is a route id (e.g. 'openrouter')
-- and fallback_depth is an integer route position. Neither can
-- identify a client or reveal a credential.
-- ============================================================

begin;

-- provider: route id of the AI route that produced the cached analysis.
-- Values are the ids emitted by the failover router (aiRouter.ts /
-- aiProviders.ts), e.g. 'novita' | 'openrouter' | 'kilo' | 'gemini' |
-- 'nvidia'. Intentionally not constrained by a CHECK: the route list is
-- owned by the edge functions and may gain providers, and a constraint
-- would then block a perfectly valid write.
alter table public.ai_analysis_cache
  add column if not exists provider text null;

comment on column public.ai_analysis_cache.provider is
  'Route id of the provider that generated this analysis (openrouter, kilo, ...). NULL = unknown, i.e. a row written before provider attribution existed. Never backfilled or derived from model.';

-- fallback_depth: 1-based position of the winning route in the failover
-- chain, so 1 = first choice succeeded, 2 = one skip before it, etc.
-- NULL = unknown (same reason as provider). Guarded so a 0 can never be
-- stored and later rendered as a bogus "Fallback #0".
alter table public.ai_analysis_cache
  add column if not exists fallback_depth integer null;

alter table public.ai_analysis_cache
  drop constraint if exists ai_analysis_cache_fallback_depth_positive;

alter table public.ai_analysis_cache
  add constraint ai_analysis_cache_fallback_depth_positive
  check (fallback_depth is null or fallback_depth >= 1);

comment on column public.ai_analysis_cache.fallback_depth is
  '1-based position of the winning route in the failover chain (1 = first choice). NULL = unknown for rows written before attribution existed.';

commit;
