-- ============================================================
-- YBS SYSTEM: ONE-TIME CLEANUP — PRE-ACTIVATION-ANCHORED RECURRING FORMS
-- (20260917000001)
--
-- One-time follow-up to 20260916000001_activation_anchored_recurring_forms.sql.
-- The OLD recurring scheduler anchored cadence to "last assignment time"
-- (due_date = assigned_at + interval), so the daily cron could queue weekly /
-- biweekly check-ins at the WRONG time (even before a client's first interval
-- had elapsed). Those wrong-time instances are still sitting in the admin
-- Forms queue (and the client queue) as unwritten, unanswered check-ins and
-- need to be removed — WITHOUT touching valid history, templates, or rules.
--
-- Deterministic discriminator (provable from data, no wall clock needed):
--   * OLD logic  set  due_date = assigned_at + interval  ->  due_date ALWAYS >  assigned_at::date
--   * NEW logic  sets due_date = activation + cycle*interval (cycle >= 1,
--     current cycle only)                                ->  due_date ALWAYS <= assigned_at::date
-- so `due_date > assigned_at::date` can only belong to an old-logic instance,
-- and `due_date <= assigned_at::date` can only belong to a new-logic instance.
--
-- Deletion scope is the intersection of ALL of:
--   * generated by a weekly / biweekly (recurring) rule trigger
--   * ledger status 'assigned' AND assessment submission_status 'pending'
--     AND assessment.submitted_at IS NULL        (still awaiting response)
--   * ZERO assessment_responses                  (no real client data)
--   * old-logic wrong-time signature above       (generated by old scheduler)
--
-- SAFETY GUARANTEES (unchanged by this migration):
--   * Deletes ONLY the wrongly-generated pending assessments. The DELETE
--     cascades assessment_responses, the form_assignment_instances ledger
--     row, and ai_analysis_cache (all ON DELETE CASCADE).
--   * submitted / reviewed history, forms with responses, and every
--     new-logic (activation-anchored) instance are UNTOUCHED.
--   * assessment_templates, form_assignment_rules, and all one-off triggers
--     (client_approval / nutrition_workout / subscription_renewal) are NOT
--     modified.
--   * The activation-anchored scheduler (assign_form_for_rule +
--     evaluate_due_recurring_form_rules, migration 20260916000001) and its
--     deterministic per-cycle dedup are NOT redefined here and keep working
--     unchanged. After this cleanup the daily sweeper regenerates ONLY a
--     client's correctly-dated current cycle (never a back-fill).
--
-- Pre-apply dry-run: run ybs-cleanup-dryrun.sql in the SQL editor and review
-- the `safe_to_delete` rows before executing this migration.
-- ============================================================

WITH doomed AS (
    SELECT a.id
    FROM public.form_assignment_instances fai
    JOIN public.assessments a ON a.id = fai.assessment_id
    WHERE fai.trigger_type IN ('weekly', 'biweekly')
      AND fai.status = 'assigned'
      AND a.submission_status = 'pending'
      AND a.submitted_at IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM public.assessment_responses ar
          WHERE ar.assessment_id = a.id
      )
      AND a.due_date IS NOT NULL
      AND a.due_date > fai.assigned_at::date
)
DELETE FROM public.assessments a
USING doomed d
WHERE a.id = d.id;